import type { Metadata } from "next";
import { Red_Hat_Text, Inter } from "next/font/google";
import { headers, cookies } from "next/headers";
import { getDictionary } from "@/i18n";
import { parseLocale, defaultLocale } from "@/i18n/config";
import { DictionaryProvider } from "@/i18n/DictionaryProvider";
import type { Locale } from "@/i18n/config";
import CustomCursor from "@/ui/CustomCursor";
import "./globals.css";

const redHatText = Red_Hat_Text({
  variable: "--font-red-hat-text",
  subsets: ["latin", "latin-ext"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const saved = cookieStore.get("locale")?.value as Locale | undefined;

  let locale: Locale;
  if (saved && (saved === "en" || saved === "ru")) {
    locale = saved;
  } else {
    const headersList = await headers();
    const acceptLang = headersList.get("accept-language");
    locale = parseLocale(acceptLang);
  }

  const dictionary = await getDictionary(locale);

  return (
    <html lang={locale}>
      <body
        className={`${redHatText.variable} ${inter.variable} ${redHatText.className} antialiased`}
      >
        <CustomCursor />
        <DictionaryProvider dictionary={dictionary}>
          {children}
        </DictionaryProvider>
      </body>
    </html>
  );
}
